version: '3.7'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: apps/app/Dockerfile 
    restart: always
    ports: 
      - "4200:80"
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports: 
      - "3333:3333"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:5.0.5-alpine
    restart: always
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgress_password
      - PG_PORT=5432
  