version: '3.7'

services:
  api:
    container_name: container_api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports: 
      - "3333:3333"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
      - postgres
    volumes: 
      - /usr/be/api/node_modules
      - .:/usr/be/api
  redis:
    image: redis:5.0.5-alpine
    restart: always
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=postgress_password
      - PG_PORT=5432
