
apiVersion: skaffold/v1beta13
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: kocuna/api
      context: .
      docker:
        dockerfile: apps/api/Dockerfile
      sync:
        infer:
        - 'apps/api/**/*.ts'
deploy:
  kubectl:
    manifests:
      - k8s/api-deployment.yml
