version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/kocuna
    steps:
      - checkout
      - run:
          name: app npm install
          command: npm install
      - run:
          name: front-end unit tests
          command: npm run affected:test
  deploy:
    docker:
      - image: google/cloud-sdk:261.0.0-alpine
    working_directory: ~/kocuna
    steps:
      - checkout
      - run:
          name: install extra packages
          command: |
            gcloud components install kubectl
            apk add docker
      - run:
          name: authenticate Google Cloud SKD
          command: |
            ./tools/scripts/deploy.sh
workflows:
  version: 2

  kocuna_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
