version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/kocuna
    steps:
      - checkout
      - run:
          name: app npm install
          command: npm install
      - run:
          name: front-end unit tests
          command: npm run affected:test
  deploy:
    docker:
      - image: google/cloud-sdk:261.0.0-alpine
    working_directory: ~/kocuna
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: install extra packages
          command: |
            gcloud components install kubectl
            apk add docker
      - run:
          name: authenticate Google Cloud SKD
          environment:
            CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
          command: |
            .circleci/authenticateGoogleCloudSDK.sh
      - run:
          name: Build and push docker images
          command: |
            .circleci/buildAndPushDockerImages.sh
      - run:
          name: deploy
          environment:
            CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
          command: |
            .circleci/deploy.sh
workflows:
  version: 2

  kocuna_workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
